# Generated by Django 3.1.1 on 2020-12-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis-match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doubles',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('NB', 'Non-binary')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mixed_doubles',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='singles',
            field=models.BooleanField(null=True),
        ),
    ]
